import os

BASE_DIR = r"C:\Users\user\Documents\shopee_orders_etl"
SHOP_ACCOUNT_MAP_PATH = r"C:\Users\user\Documents\shopee_orders_etl\config\shop_account_map.csv"

INPUT_DIR = os.path.join(BASE_DIR, "input")
OUTPUT_DIR = os.path.join(BASE_DIR, "output")
OUTPUT_CSV_PATH = os.path.join(OUTPUT_DIR, "GTD_master_orders_cleaned.csv")

COLUMN_MAPPING = {
    "店鋪名稱": "shop_name",
    # "店鋪帳號": "shop_account",  # 店鋪帳號目前ETL會補空字串，不來自原始檔
    "買家帳號": "buyer_username",
    "訂單日期": "order_date",
    "訂單編號": "order_sn",
    "訂單編號(從這邊貼上)": "order_sn",
    "訂單狀態": "order_status",
    "不成立原因": "cancellation_reason",
    "退貨 / 退款狀態": "return_refund_status",
    "訂單成立日期": "order_creation_timestamp",
    "商品 總價": "product_total_price",
    "買家支付運費": "buyer_paid_shipping_fee",
    "蝦皮補助運費": "shopee_shipping_subsidy",
    "退貨運費": "return_shipping_fee",
    "買家總支付金額": "total_amount_paid_by_buyer",
    "蝦皮補貼金額": "shopee_subsidy_amount",
    "蝦幣折抵": "shopee_coin_offset",
    "銀行信用卡活動折抵": "credit_card_promotion_discount",
    "優惠代碼": "voucher_code",
    "賣場優惠券": "seller_voucher",
    "賣家蝦幣回饋券": "seller_coin_cashback_voucher",
    "優惠券": "voucher",
    "成交手續費": "transaction_fee",
    "其他服務 費": "other_service_fee",
    "金流與系統處理費": "payment_processing_fee",
    "分期付款期數": "installment_plan_periods",
    "金流與系統處理費率": "payment_processing_fee_rate",
    "成交手續費規則名稱": "transaction_fee_rule_name",
    "商品名稱": "product_name",
    "商品選項名稱": "product_variation",
    "商品原價": "product_original_price",
    "商品活動價格": "product_campaign_price",
    "主商品貨號": "product_sku_main",
    "商品選項貨號": "product_sku_variation",
    "數量": "quantity",
    "退貨數量": "return_quantity",
    "促銷 組合指標": "promo_bundle_indicator",
    "蝦皮促銷組合折扣:促銷組合標籤": "promo_bundle_discount_label",
    "收件地址": "recipient_address",
    "收件者電話 (若您是自行配送請使用後方蝦皮專線和包裹查詢碼聯繫買家)": "recipient_phone",
    "蝦皮專線和包裹查詢碼  (請複製下方完整編號提供給您配合的物流商當做聯絡電話)": "shopee_hotline_and_tracking_code",
    "取件門市店號": "pickup_store_id",
    "城市": "recipient_city",
    "行政區": "recipient_district",
    "郵遞區號": "recipient_postal_code",
    "收件者姓名": "recipient_name",
    "寄送方式": "shipping_method",
    "出貨方式": "shipping_provider",
    "備貨時間": "days_to_ship",
    "付款方式": "payment_method",
    "最晚出貨日期": "ship_by_date",
    "包裹查詢號碼": "tracking_number",
    "買家付款時間": "buyer_payment_timestamp",
    "實際出貨時間": "actual_shipping_timestamp",
    "訂單完成時間": "order_completion_timestamp",
    "買家備註": "buyer_note",
    "備註": "seller_note",
}

FINAL_COLUMN_ORDER = [
    "shop_name",
    "shop_account",  # ETL時補空字串
    "processing_date",  # ETL新增處理日期
    "order_date",
    "order_sn",
    "order_status",
    "cancellation_reason",
    "return_refund_status",
    "buyer_username",
    "order_creation_timestamp",
    "product_total_price",
    "buyer_paid_shipping_fee",
    "shopee_shipping_subsidy",
    "return_shipping_fee",
    "total_amount_paid_by_buyer",
    "shopee_subsidy_amount",
    "shopee_coin_offset",
    "credit_card_promotion_discount",
    "voucher_code",
    "seller_voucher",
    "seller_coin_cashback_voucher",
    "voucher",
    "transaction_fee",
    "other_service_fee",
    "payment_processing_fee",
    "installment_plan_periods",
    "payment_processing_fee_rate",
    "transaction_fee_rule_name",
    "product_name",
    "product_variation",
    "product_original_price",
    "product_campaign_price",
    "product_sku_main",
    "product_sku_variation",
    "quantity",
    "return_quantity",
    "promo_bundle_indicator",
    "promo_bundle_discount_label",
    "recipient_address",
    "recipient_phone",
    "shopee_hotline_and_tracking_code",
    "pickup_store_id",
    "recipient_city",
    "recipient_district",
    "recipient_postal_code",
    "recipient_name",
    "shipping_method",
    "shipping_provider",
    "days_to_ship",
    "payment_method",
    "ship_by_date",
    "tracking_number",
    "buyer_payment_timestamp",
    "actual_shipping_timestamp",
    "order_completion_timestamp",
    "buyer_note",
    "seller_note",
]
